[project]
name = "anycaptcha"
version = "1.6.0"
description = "All captcha solving services in one lib"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "better-proxy>=1.3",
    "filetype>=1.2.0",
    "httpx>=0.27",
    "pydantic>=1",
]
